apiVersion: v2
name: grafana-stack-umbrella
description: A Helm umbrella chart for the Grafana Stack (Mimir, Loki, Tempo, Grafana, Alloy)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: minio
    version: 5.4.0
    repository: "https://charts.min.io/"

  - name: mimir-distributed
    version: "6.0.5"
    repository: "https://grafana.github.io/helm-charts"
  - name: loki
    version: "6.51.0"
    repository: "https://grafana.github.io/helm-charts"
  - name: tempo
    version: 1.61.3
    repository: "https://grafana.github.io/helm-charts"
  - name: grafana
    version: "10.5.15"
    repository: "https://grafana.github.io/helm-charts"
  - name: alloy
    version: "1.5.3"
    repository: "https://grafana.github.io/helm-charts"
