apiVersion: v1
kind: Pod
metadata:
  name: test-metrics-pod
  labels:
    app: test-metrics
  annotations:
    # Annotation-based scraping test (Alloy pipeline 5)
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
    # profiles.grafana.com/memory.scrape: "true"
    # profiles.grafana.com/memory.port_name: "metrics"
    # profiles.grafana.com/cpu.scrape: "true"
    # profiles.grafana.com/cpu.port_name: "metrics"
    # profiles.grafana.com/goroutine.scrape: "true"
    # profiles.grafana.com/goroutine.port_name: "metrics"
    # profiles.grafana.com/service_repository: 'https://github.com/grafana/alloy'
    # profiles.grafana.com/service_git_ref: 'v1.8.1'

spec:
  containers:
    - name: prometheus-example-app
      image: quay.io/brancz/prometheus-example-app:v0.3.0
      ports:
        - name: metrics
          containerPort: 8080
---
# apiVersion: monitoring.coreos.com/v1
# kind: PodMonitor
# metadata:
#   name: test-metrics-monitor
#   labels:
#     release: {{ .Release.Name }}
# spec:
#   selector:
#     matchLabels:
#       app: test-metrics
#   podMetricsEndpoints:
#     - port: metrics
#       path: /metrics
#       interval: 15s
